appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: HIaUBfBPYsKTfS+oolCfaCfMJN4NbT2ocN+5fNhzdnj3PYdbo2xyOxE3lVvLw62o88m2ahxOgdqpOeBG++tMyYSwPBB2NQSLIhiyEP1fqBX6ZfqTpROHlalGK9LcnXuDVreQm8FZFs58mHT2zGyTEIqne3QLvqCFRE7e9pFl08NwRpNF0Sy9fgAKs9s6wuX8j7ukmrdSNQG1PgyJKmsxtg32UIalzhSLkan+hD3yVwGKuj3ZZpmfnDwm0acEpAzLU/oRTGggjtkdkKaVUBABRBy3zidOiP3sEXpUVJhXA3Ma5JQ95LOkWG8oc1fnT6ppL7eGmSKd3767Lc+FMf0yCsOP7ELmXO51UqTpThvaf/6ze3Y65Qr9HrPBPbSKmhPqNwm0WDwRh1EiMkvLCRdiN8fSQ9npttieXEi2JDOQYzEdj6FyLPBmAoyDpvlCSYKNSKcP93xD25+XoxYt0vX6PC/nWFu9gI1ldZ0T3M0pBTmXsOR+SLXNfZ0uR+iOqTP0gTLpvWNlWF5VR5G+CR8ZBzKAejHcTsQggmDJ2ttcg9iGTa8ujZLpmcIwZ5OaKXC+Pn6cp5cBFarDU/Bo9qN56smAAj1RrAJPW536o1Wl9KBSuhpFuZdMzCSAf6gzkxY8J+rjcCs+LiiZSBe6K4ZaeodGavAsh9QKaTe69iKoRXE=
